### ISSUE TITLE
session_id occasionally returned as 0

### ISSUE THREAD

**Issue by dpdutcher** [simonsobs/sodetlib#217]
Traceback:
```
2022-03-11T18:06:43+0000 ufm_biasstep_sodetlib.py: Traceback (most recent call last):
  File "/sodetlib/sodetlib/operations/bias_steps.py", line 876, in take_bias_steps
    bsa.run_analysis(save=True, **_analysis_kwargs)
  File "/sodetlib/sodetlib/operations/bias_steps.py", line 265, in run_analysis
    self._load_am(arc=arc)
  File "/sodetlib/sodetlib/operations/bias_steps.py", line 316, in _load_am
    self.am = sdl.load_session(self.meta['stream_id'], self.sid)
  File "/sodetlib/sodetlib/stream.py", line 94, in load_session
    base_dir=base_dir)
  File "/sodetlib/sodetlib/stream.py", line 36, in get_session_files
    os.path.join(subdir, f) for f in os.listdir(subdir)
FileNotFoundError: [Errno 2] No such file or directory: '/data/so/timestreams/0/crate1slot2'
```

I've run into this problem a few times now, in the context of running bias steps on three modules at once via OCS, running sodetlib scripts in the pysmurf-controller image. I suspect the issue is due to the lines below, and that the number of attempts or the wait time needs to be increased. I doubled the attempts to 10 and it still had a failure, and I'm now attempting increasing the wait time at each step to 0.5s. I think this is symptomatic of a bigger issue, though.

https://github.com/simonsobs/sodetlib/blob/60592c8d34b32a7d4c0899438df141465644c0a9/sodetlib/stream.py#L162-L169

**Comment by dpdutcher** [comment]
Of course, the day I close this, it happens again.

**Comment by jlashner** [comment]
Unfortunately this issue is a bit difficult to debug without a way to reliably reproduce. I think a good next step to give us more info is to modify the Smurf streamer to track how long exactly it's taking for the session-id to be set, then we can see if that's actually the issue and work on minimizing that time if it is

**Comment by jlashner** [comment]
Can you link to the paths to the generated g3 files on simons1?

**Comment by dpdutcher** [comment]
Ah, it wasn't during IVs actually, but a timestream-taking step in between IVs. More info, for posterity: 
```
#take 30s timestream for noise
sid = sdl.take_g3_data(S, 30)
am = sdl.load_session(cfg.stream_id, sid, base_dir=cfg.sys['g3_dir'])
```

2022-09-09T05:01:06+0000 uxm_bath_iv_noise.py: [ 2022-09-09 05:01:06 ]  Done waiting.
2022-09-09T05:01:06+0000 uxm_bath_iv_noise.py: [ 2022-09-09 05:01:06 ]  Waiting for g3 file to close out
2022-09-09T05:01:08+0000 Traceback (most recent call last):
  File "/readout-script-dev/ddutcher/uxm_bath_iv_noise.py", line 71, in <module>
2022-09-09T05:01:08+0000     am = sdl.load_session(cfg.stream_id, sid, base_dir=cfg.sys['g3_dir'])
  File "/sodetlib/sodetlib/stream.py", line 94, in load_session
2022-09-09T05:01:08+0000     base_dir=base_dir)
  File "/sodetlib/sodetlib/stream.py", line 36, in get_session_files
    os.path.join(subdir, f) for f in os.listdir(subdir)
FileNotFoundError: [Errno 2] No such file or directory: '/data/timestreams/0/crate1slot5'

The g3 file being produced during the above should be `simons1:/mnt/so1/data/pton-rd/timestreams/16626/crate1slot5/1662699635_000.g3`

**Comment by jlashner** [comment]
G3 file looks very normal:
```
/mnt/so1/data/pton-rd/timestreams/16626/crate1slot5/1662699635_000.g3
--------------------
  0 |  Observation | 09-Sep-2022:05:00:35.486328000 |             
  1 |       Wiring | 09-Sep-2022:05:00:35.878648000 |             
  2 |       Wiring | 09-Sep-2022:05:00:35.985705000 |             
  3 |         Scan | 09-Sep-2022:05:00:36.176626000 |    400 samps
  4 |         Scan | 09-Sep-2022:05:00:38.162020000 |    400 samps
  5 |         Scan | 09-Sep-2022:05:00:40.172527000 |    400 samps
  6 |         Scan | 09-Sep-2022:05:00:42.156740000 |    400 samps
  7 |         Scan | 09-Sep-2022:05:00:44.189657000 |    400 samps
  8 |         Scan | 09-Sep-2022:05:00:46.192394000 |    400 samps
  9 |         Scan | 09-Sep-2022:05:00:48.153464000 |    400 samps
 10 |         Scan | 09-Sep-2022:05:00:50.151407000 |    401 samps
 11 |         Scan | 09-Sep-2022:05:00:52.167145000 |    400 samps
 12 |         Scan | 09-Sep-2022:05:00:54.171431000 |    400 samps
 13 |       Wiring | 09-Sep-2022:05:00:55.286064000 |             
 14 |         Scan | 09-Sep-2022:05:00:56.184687000 |    400 samps
 15 |         Scan | 09-Sep-2022:05:00:58.188366000 |    400 samps
 16 |         Scan | 09-Sep-2022:05:01:00.189746000 |    400 samps
 17 |         Scan | 09-Sep-2022:05:01:02.156429000 |    400 samps
 18 |         Scan | 09-Sep-2022:05:01:04.144158000 |    400 samps
 19 |       Wiring | 09-Sep-2022:05:01:05.286337000 |             
 20 |       Wiring | 09-Sep-2022:05:01:05.836246000 |             
 21 |       Wiring | 09-Sep-2022:05:01:06.004880000 |             
 22 |       Wiring | 09-Sep-2022:05:01:06.007578000 |             
 23 |       Wiring | 09-Sep-2022:05:01:06.010637000 |             
 24 |         Scan | 09-Sep-2022:05:01:06.189582000 |    362 samps
 25 |  Observation | 09-Sep-2022:05:01:08.029525000 |             
```
so I don't necessarily think there's a buffering issue or problem with the streamer. To be honest, the file time seems very close to 30 seconds, so I"m not entirely sure it's being stopped by this block: https://github.com/simonsobs/sodetlib/blob/6a3f230cf5452503432c8028cfcee35fc442e49b/sodetlib/stream.py#L164-L169
We should add a log statement (or raise an error maybe?) if it goes through all 10 iterations and still thinks the session-id is 0.

**Comment by jlashner** [comment]
what server is this being run on?

**Comment by dpdutcher** [comment]
smurf-srv15

**Comment by jlashner** [comment]
ah interesting.... does this only happen when running with the pysmurf-controller?

**Comment by dpdutcher** [comment]
My experience is skewed since I run just about everything through the pysmurf-controller, certainly any long-duration operations or overnight data sets.

**Comment by jlashner** [comment]
Ok, I try to address the problem in this PR: https://github.com/simonsobs/sodetlib/pull/289
where I change the session-id retrieval to `stream_g3_off` to avoid race conditions, and this will also try to extract it from the current g3file if it happens to still be 0 for whatever reason. I _think_ that should solve the issue. If we can test it to make sure it doesn't break anything, then I think I'm happy merging it and seeing if it helps avoid this issue.

**Comment by jlashner** [comment]
So a problem that's come up in newer builds of the SO/pysmurf dockers is that the epics `caget` default parameters have actually changed, in particular the `use_monitor` default has switched from False to True, meaning it will read from cached values instead of actually querying the register...... I think you're still using a version of the docker before this switch happened, but now I'm wondering if this problem could actually be caused by internal caching in epics. 

I think we should use `caget(use_monitor=False)` wherever we read data, and see if that solves this issue.
